# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hw26' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hw26
	pod 'Firebase/Analytics'
  	pod 'Firebase/Auth'
  	pod 'Firebase/Crashlytics'
end
